services:
    - docker

install:
    - docker-compose up -d
    - docker-compose exec php php -v
    - docker-compose exec php composer install

script:
    - docker-compose exec php ./vendor/bin/phpunit
    - docker-compose exec php php ./src/app.php
